// Generates supabase/seed.sql config rows from packages/core/src/config.ts (single source of truth).
// Run: pnpm gen:seed
import { writeFileSync } from "node:fs";
import { CONFIG_DEFAULTS } from "../packages/core/src/config.ts";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const rows = Object.entries(CONFIG_DEFAULTS).map(
  ([key, { value, note }]) => `  (${q(key)}, ${q(JSON.stringify(value))}::jsonb, null, ${q(note)})`,
);
const sql = `-- GENERATED by scripts/gen-seed-config.ts. Do not edit by hand.
-- All values are UNVERIFIED placeholders (verified_at = null). See docs/VERIFY.md.
insert into public.config (key, value, verified_at, note) values
${rows.join(",\n")}
on conflict (key) do nothing;
`;
writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql);
console.log(`wrote ${rows.length} config rows to supabase/seed.sql`);
